### ISSUE TITLE
[Bug] Failed to publish symbols

### ISSUE THREAD

**Issue by Favna** [rohith/publish-nuget#30]
First of all many thanks for this action. It has saved me so much pain!!

I see that since a more recent publish you now default to also pushing symbols, this however made my CI exit out with exit code 1 as it was unable to find a file named `*.symbols.nupkg`. For now I disabled it by passing `INCLUDE_SYMBOLS: false` to the config but I wanted to bring it up anyway. Below is the full raw log of the action and this is where it ran and failed: https://github.com/favware/graphql-pokemon/runs/639296241?check_suite_focus=true

This is the CSPROJ file that it uses for publishing: https://github.com/favware/graphql-pokemon/blob/master/generated/dotnet/Favware.Graphqlpokemon.csproj
Note that the (single) `.cs` file that it publishes is autogenerated by the github action and never tracked in Git, therefore it is not in the repository. That said, here is a version of it: https://hasteb.in/comoroni.cs

<details> <summary> Full raw action log </summary>

```
2020-05-02T19:34:29.7073157Z ##[group]Run actions/download-artifact@v2-preview
2020-05-02T19:34:29.7073662Z with:
2020-05-02T19:34:29.7074101Z   name: changelog_bundle
2020-05-02T19:34:29.7074548Z env:
2020-05-02T19:34:29.7074989Z   DOTNET_CLI_TELEMETRY_OPTOUT: true
2020-05-02T19:34:29.7075446Z ##[endgroup]
2020-05-02T19:34:29.8509681Z Directory structure has been setup for the artifact
2020-05-02T19:34:29.8517789Z Total number of files that will be downloaded: 1
2020-05-02T19:34:29.9054512Z Artifact changelog_bundle was downloaded to /home/runner/work/graphql-pokemon/graphql-pokemon
2020-05-02T19:34:29.9055609Z Artifact download has finished successfully
2020-05-02T19:34:29.9207304Z ##[group]Run actions/setup-dotnet@v1
2020-05-02T19:34:29.9207792Z with:
2020-05-02T19:34:29.9208251Z   dotnet-version: 3.1.201
2020-05-02T19:34:29.9208714Z env:
2020-05-02T19:34:29.9209176Z   DOTNET_CLI_TELEMETRY_OPTOUT: true
2020-05-02T19:34:29.9209713Z ##[endgroup]
2020-05-02T19:34:30.0781357Z [command]/home/runner/work/_actions/actions/setup-dotnet/v1/externals/get-os-distro.sh
2020-05-02T19:34:30.0955884Z Primary:linux-x64
2020-05-02T19:34:30.1014124Z Legacy:ubuntu.18.04
2020-05-02T19:34:30.1015188Z Checking tool cache
2020-05-02T19:34:30.1018819Z Getting a download url 3.1.201
2020-05-02T19:34:31.8666692Z Extracting Package /home/runner/work/_temp/770d3a80-8f9c-4ee1-87c0-4a8962a1d55d
2020-05-02T19:34:31.8683402Z [command]/bin/tar xz -C /home/runner/work/_temp/fd2b2875-3f51-4cd6-8efc-589878f82a5b -f /home/runner/work/_temp/770d3a80-8f9c-4ee1-87c0-4a8962a1d55d
2020-05-02T19:34:34.9351463Z Caching tool
2020-05-02T19:34:37.3037328Z Successfully installed 3.1.201
2020-05-02T19:34:37.3310158Z ##[group]Run rohith/publish-nuget@v2
2020-05-02T19:34:37.3310635Z with:
2020-05-02T19:34:37.3311113Z   PROJECT_FILE_PATH: generated/dotnet/Favware.Graphqlpokemon.csproj
2020-05-02T19:34:37.3311622Z   PACKAGE_NAME: Favware.Graphqlpokemon
2020-05-02T19:34:37.3312098Z   TAG_COMMIT: false
2020-05-02T19:34:37.3312991Z   NUGET_KEY: ***
2020-05-02T19:34:37.3313451Z   VERSION_REGEX: <Version>(.*)<\/Version>
2020-05-02T19:34:37.3313914Z   TAG_FORMAT: v*
2020-05-02T19:34:37.3314496Z   NUGET_SOURCE: https://api.nuget.org
2020-05-02T19:34:37.3314975Z   NUGET_SYMBOL_SOURCE: https://api.nuget.org
2020-05-02T19:34:37.3315440Z   INCLUDE_SYMBOLS: true
2020-05-02T19:34:37.3315862Z env:
2020-05-02T19:34:37.3316287Z   DOTNET_CLI_TELEMETRY_OPTOUT: true
2020-05-02T19:34:37.3316732Z   DOTNET_ROOT: /opt/hostedtoolcache/dncs/3.1.201/x64
2020-05-02T19:34:37.3317186Z ##[endgroup]
2020-05-02T19:34:37.3742046Z Project Filepath: generated/dotnet/Favware.Graphqlpokemon.csproj
2020-05-02T19:34:37.3745683Z Version Filepath: generated/dotnet/Favware.Graphqlpokemon.csproj
2020-05-02T19:34:37.3746460Z Version Regex: /<Version>(.*)<\/Version>/
2020-05-02T19:34:37.3747690Z Version: 3.0.2
2020-05-02T19:34:37.3750450Z Package Name: Favware.Graphqlpokemon
2020-05-02T19:34:37.4677585Z âœ¨ found new version (3.0.2) of Favware.Graphqlpokemon
2020-05-02T19:34:37.4678840Z NuGet Source: https://api.nuget.org
2020-05-02T19:34:37.4679603Z NuGet Symbol Source: https://api.nuget.org
2020-05-02T19:34:37.4683335Z executing: [dotnet build -c Release generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:37.5828017Z 
2020-05-02T19:34:37.5878252Z Welcome to .NET Core 3.1!
2020-05-02T19:34:37.5879828Z ---------------------
2020-05-02T19:34:37.5880550Z SDK Version: 3.1.201
2020-05-02T19:34:37.5880907Z 
2020-05-02T19:34:37.5881831Z ----------------
2020-05-02T19:34:37.5882894Z Explore documentation: https://aka.ms/dotnet-docs
2020-05-02T19:34:37.5883866Z Report issues and find source on GitHub: https://github.com/dotnet/core
2020-05-02T19:34:37.5885178Z Find out what's new: https://aka.ms/dotnet-whats-new
2020-05-02T19:34:37.5886466Z Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
2020-05-02T19:34:37.5887823Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
2020-05-02T19:34:37.5889063Z Write your first app: https://aka.ms/first-net-core-app
2020-05-02T19:34:37.5890282Z --------------------------------------------------------------------------------------
2020-05-02T19:34:38.0166068Z Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
2020-05-02T19:34:38.0166762Z Copyright (C) Microsoft Corporation. All rights reserved.
2020-05-02T19:34:38.0167063Z 
2020-05-02T19:34:53.5611470Z   Restore completed in 14.66 sec for /home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj.
2020-05-02T19:34:54.9728321Z   Favware.Graphqlpokemon -> /home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.dll
2020-05-02T19:34:55.1722321Z ##[warning]/opt/hostedtoolcache/dncs/3.1.201/x64/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.dll' is not added because the package already contains file 'lib/netcoreapp3.1/Favware.Graphqlpokemon.dll' [/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:55.1732785Z ##[warning]/opt/hostedtoolcache/dncs/3.1.201/x64/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.xml' is not added because the package already contains file 'lib/netcoreapp3.1/Favware.Graphqlpokemon.xml' [/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:55.2063189Z   Successfully created package '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/Favware.Graphqlpokemon.3.0.2.nupkg'.
2020-05-02T19:34:55.2205203Z 
2020-05-02T19:34:55.2206110Z Build succeeded.
2020-05-02T19:34:55.2208721Z 
2020-05-02T19:34:55.2213407Z ##[warning]/opt/hostedtoolcache/dncs/3.1.201/x64/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.dll' is not added because the package already contains file 'lib/netcoreapp3.1/Favware.Graphqlpokemon.dll' [/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:55.2217091Z ##[warning]/opt/hostedtoolcache/dncs/3.1.201/x64/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.xml' is not added because the package already contains file 'lib/netcoreapp3.1/Favware.Graphqlpokemon.xml' [/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:55.2220624Z     2 Warning(s)
2020-05-02T19:34:55.2221104Z     0 Error(s)
2020-05-02T19:34:55.2223147Z 
2020-05-02T19:34:55.2223815Z Time Elapsed 00:00:17.14
2020-05-02T19:34:55.2397706Z executing: [dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release generated/dotnet/Favware.Graphqlpokemon.csproj -o .]
2020-05-02T19:34:55.5266329Z Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
2020-05-02T19:34:55.5267946Z Copyright (C) Microsoft Corporation. All rights reserved.
2020-05-02T19:34:55.5268979Z 
2020-05-02T19:34:56.2613525Z ##[warning]/opt/hostedtoolcache/dncs/3.1.201/x64/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.dll' is not added because the package already contains file 'lib/netcoreapp3.1/Favware.Graphqlpokemon.dll' [/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:56.2622741Z ##[warning]/opt/hostedtoolcache/dncs/3.1.201/x64/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.xml' is not added because the package already contains file 'lib/netcoreapp3.1/Favware.Graphqlpokemon.xml' [/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:56.3053168Z   Successfully created package '/home/runner/work/graphql-pokemon/graphql-pokemon/Favware.Graphqlpokemon.3.0.2.nupkg'.
2020-05-02T19:34:56.3217946Z ##[warning]/opt/hostedtoolcache/dncs/3.1.201/x64/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File '/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/bin/Release/netcoreapp3.1/Favware.Graphqlpokemon.pdb' is not added because the package already contains file 'lib/netcoreapp3.1/Favware.Graphqlpokemon.pdb' [/home/runner/work/graphql-pokemon/graphql-pokemon/generated/dotnet/Favware.Graphqlpokemon.csproj]
2020-05-02T19:34:56.3240402Z   Successfully created package '/home/runner/work/graphql-pokemon/graphql-pokemon/Favware.Graphqlpokemon.3.0.2.snupkg'.
2020-05-02T19:34:56.3458754Z Generated Package(s): Favware.Graphqlpokemon.3.0.2.nupkg, Favware.Graphqlpokemon.3.0.2.snupkg
2020-05-02T19:34:56.3464906Z executing: [dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k *** -ss https://api.nuget.org/v3/index.json -sk *** --skip-duplicate]
2020-05-02T19:34:57.5277931Z Pushing Favware.Graphqlpokemon.3.0.2.nupkg to 'https://www.nuget.org/api/v2/package'...
2020-05-02T19:34:57.5279963Z   PUT https://www.nuget.org/api/v2/package/
2020-05-02T19:34:57.5299018Z /home/runner/work/_actions/rohith/publish-nuget/v2/index.js:25
2020-05-02T19:34:57.5300573Z   Created https://www.nuget.org/api/v2/package/ 703ms
2020-05-02T19:34:57.5301777Z Your package was pushed.
2020-05-02T19:34:57.5302847Z error: File does not exist (*.symbols.nupkg).
2020-05-02T19:34:57.5303494Z 
2020-05-02T19:34:57.5304094Z 
2020-05-02T19:34:57.5305219Z Usage: dotnet nuget push [arguments] [options]
2020-05-02T19:34:57.5305849Z 
2020-05-02T19:34:57.5306799Z Arguments:
2020-05-02T19:34:57.5307838Z   [root]  Specify the path to the package and your API key to push the package to the server.
2020-05-02T19:34:57.5308587Z 
2020-05-02T19:34:57.5309540Z Options:
2020-05-02T19:34:57.5310913Z   -h|--help                      Show help information
2020-05-02T19:34:57.5312601Z   --force-english-output         Forces the application to run using an invariant, English-based culture.
2020-05-02T19:34:57.5314147Z   -s|--source <source>           Specifies the server URL
2020-05-02T19:34:57.5315853Z   -ss|--symbol-source <source>   Specifies the symbol server URL. If not specified, nuget.smbsrc.net is used when pushing to nuget.org.
2020-05-02T19:34:57.5317995Z   -t|--timeout <timeout>         Specifies the timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
2020-05-02T19:34:57.5319542Z   -k|--api-key <apiKey>          The API key for the server.
2020-05-02T19:34:57.5320967Z   -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
2020-05-02T19:34:57.5322589Z   -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
2020-05-02T19:34:57.5324301Z   -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
2020-05-02T19:34:57.5325888Z   --no-service-endpoint          Does not append "api/v2/package" to the source URL.
2020-05-02T19:34:57.5327637Z   --interactive                  Allow the command to block and require manual action for operations like authentication.
2020-05-02T19:34:57.5329241Z   --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
2020-05-02T19:34:57.5329681Z 
2020-05-02T19:34:57.5335231Z ##[error]ðŸ˜­ error: File does not exist (*.symbols.nupkg).
2020-05-02T19:34:57.5337026Z         throw new Error(msg)
2020-05-02T19:34:57.5337476Z         ^
2020-05-02T19:34:57.5337706Z 
2020-05-02T19:34:57.5338218Z Error: error: File does not exist (*.symbols.nupkg).
2020-05-02T19:34:57.5339123Z     at Action._printErrorAndExit (/home/runner/work/_actions/rohith/publish-nuget/v2/index.js:25:15)
2020-05-02T19:34:57.5339933Z     at Action._pushPackage (/home/runner/work/_actions/rohith/publish-nuget/v2/index.js:78:18)
2020-05-02T19:34:57.5345110Z     at IncomingMessage.<anonymous> (/home/runner/work/_actions/rohith/publish-nuget/v2/index.js:114:30)
2020-05-02T19:34:57.5345776Z     at IncomingMessage.emit (events.js:215:7)
2020-05-02T19:34:57.5346234Z     at endReadableNT (_stream_readable.js:1184:12)
2020-05-02T19:34:57.5346714Z     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-05-02T19:34:57.5416138Z Post job cleanup.
2020-05-02T19:34:57.6455500Z [command]/usr/bin/git version
2020-05-02T19:34:57.6537852Z git version 2.26.0
2020-05-02T19:34:57.6689063Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-05-02T19:34:57.6690530Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-05-02T19:34:57.6921011Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-05-02T19:34:57.6952226Z http.https://github.com/.extraheader
2020-05-02T19:34:57.6959266Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-05-02T19:34:57.6997389Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-05-02T19:34:57.7282848Z Cleaning up orphan processes
2020-05-02T19:34:57.7465806Z Terminate orphan process: pid (3071) (dotnet)
```

</details>

As an aside, I assume the `NUGET_SOURCE` option is so we can use this action to publish to GitHub. If this is correct I would love it if you could include some instructions in the README for setting this up both in the workflow file as well as any config (if any at all) required to set in the csproj file. Coming from a NodeJS background and only publishing C# for end-users that's all way above my knowledge level right now.

**Comment by AraHaan** [comment]
look in #21 also

**Comment by AraHaan** [comment]
@Favna I think you need to migrate to the ``.snupkg`` extension for now. Besides ``.snupkg`` is newer and shorter on file name. While same format as the ``.nupkg`` being a zip file renamed, it might be the thing that makes it work.

**Comment by Favna** [comment]
If this action can be configured to do so then by all means sure (I don't see an option for it...). Take note that this sentence from my original message is extremely important:
> Note that the (single) .cs file that it publishes is autogenerated by the github action and never tracked in Git

Or in other words, I control basically nothing of the build / publish process *except* the csproj file. Everything else is either autogenerated by the continuous delivery pipeline, or generated by this action (also in said continuous  pipeline)

Right now this is my implementation of this action: https://github.com/favware/graphql-pokemon/blob/5e1126005808024fc26cec5f6b470cd52ee6ebd3/.github/workflows/continuous-delivery.yml#L326-L333
And this is the csproj I target: https://github.com/favware/graphql-pokemon/blob/master/generated/dotnet/Favware.Graphqlpokemon.csproj

---

Disclaimer: I've never really done any .NET development, I'm publishing this class for other end-users to implement my GraphQL API in their projects. I literally have zero to nill knowledge of .NET's inner workings.

**Comment by AraHaan** [comment]
I see, I know .NET, but have zero to nil knowledge on making github actions from scratch either sadly.

**Comment by AraHaan** [comment]
oh and sorry, it seems I was wrong it still is messing up on it all. https://github.com/AraHaan/GitInformation/runs/647166313

**Comment by rohith** [comment]
@Favna @AraHaan Sorry for the trouble 🙏 

I was in doubt when pushing it & I see my fears have come true. I'm busy with my work life right now so I can only properly fix this on the weekend meanwhile a quick workaround would be to add `INCLUDE_SYMBOLS: false` or replace `publish-nuget@v2` with `publish-nuget@v2.3.0` in your action file

I'll post an update here once it's fixed

**Comment by Favna** [comment]
Thanks for the update Rohith!

**Comment by AraHaan** [comment]
It seems because of the fact that the marketplace example using the v2 one and as such people that copy paste from that results in this issue here.

**Comment by AraHaan** [comment]
hmm I tried what they said and it still produces issues: https://github.com/AraHaan/GitInformation/runs/651127299

**Comment by rohith** [comment]
`2.5.0` fixes this issue by partially reverting the changes introduced with `2.4.0`

Seems like the `dotnet nuget push` doesn't work as advertised when including symbols due to several issues with NuGet like nuget/home#9543 NuGet/Home#8589 nuget/home#5446 nuget/home#5442

Symbols are now opt-in (to be consistent with other minor releases & this is good for GPR support), either a future **MAJOR** release or nuget/home#7892 might enable it

Inputs for a specifying a different symbol source from the package source is removed (honestly I believe no one asked for it & I see it was a mistake when it's not yet properly supported by NuGet because of the above issues

**Comment by Favna** [comment]
TYVM @rohith!

**Comment by rohith** [comment]
Thanks for reporting this @Favna I almost forgot to address your question about pushing to GitHub although I see you're using some other action to do it but leaving it here just in case

As of now this action uses a specific endpoint to detect version changes in the project which is unavailable with GitHub Package Registry so GitHub is not yet supported but I'll have to find an alternative to fix that & I'll make sure to post an update here once the action supports GPR

**Comment by Favna** [comment]
@rohith I'm publishing various things in the workflow
- a dockerfile to dockerhub, google container registry and github registry
- an npm package to npm and GPR
- a nuget package to nuget. I'd still be interested to also publish this to GitHub and I was hoping your lib could help with this. It is however no priority for me at all.

**Comment by tig** [comment]
Hi. I'm confused about this issue. Does `INCLUDE_SYMBOLS: true` now work, or not?

I can't get it to work. I get `##[error]😭 error: Response status code does not indicate success: 400 (The package does not contain any symbol (.pdb) files.).`

My deploy works fine if I set `INCLUDE_SYMBOLS: false`. 

If this functionality is broken the docs should be updated to reflect that. 

If it's not supported, can someone give me a simple recipe for updating the symbols on nuget separately?


```
name: publish Terminal.Gui to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Terminal.Gui/Terminal.Gui.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Terminal.Gui
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
```

**Comment by tig** [comment]
Bump. Any thoughts on `INCLUDE_SYMBOLS`?

**Comment by dharmaturtle** [comment]
I was unable to get `INCLUDE_SYMBOLS` working. I've abandoned `snupkg` entirely and am currently using [this solution](https://github.com/dotnet/sdk/issues/1458#issuecomment-576961024) which throws everything into the DLL and "just works".
